
name: appb

type: nodejs:12

build:
    flavor: none

dependencies:
    nodejs:
        yarn: "1.22.5"

hooks:
    build: |
        # Move committed files in soon-to-be mounts into temp directory.
        chmod +x scripts/handle_mounts.sh
        ./scripts/handle_mounts.sh

        # Install dependencies and build Strapi.
        yarn --ignore-optional --frozen-lockfile 
        NODE_ENV=production yarn build

        # Allow for seeding
        ./scripts/seed_data.sh
    deploy: !include
      type: string
      path: scripts/seed_data.sh

web:
    commands:
        start: NODE_ENV=production yarn start

disk: 1024

mounts:
    # Strapi's cache directory.
    '/.cache':
        source: local
        source_path: cache
    # Allows write access to the SQLite db
    '/.tmp':
        source: local
        source_path: cache
    # Internal directory for letting us know seed has already occurred. 
    '/.seed':
        source: local
        source_path: seed
    # Unpcack directory for seeding
    '/data':
        source: local
        source_path: data
    # Uploads
    'public':
        source: local
        source_path: public
