# This file describes an application. You can have multiple applications
# in the same project.
#
# See https://docs.platform.sh/configuration/app.html

# The name of this app. Must be unique within a project.
name: app

# The runtime the application uses. Strapi not yet suppported with NodeJS 14.
type: nodejs:12

# Use Yarn instead of npm.
build:
    flavor: none

# Build dependencies. 
dependencies:
    nodejs:
        yarn: "1.22.5"

# The hooks executed at various points in the lifecycle of the application.
hooks:
    # The build hook runs after yarn has been downloaded.
    # No services are available but the disk is writeable.
    build: |
        # Move committed files in soon-to-be mounts into temp directory.
        chmod +x scripts/handle_mounts.sh
        ./scripts/handle_mounts.sh

        # Install dependencies and build Strapi.
        yarn --ignore-optional --frozen-lockfile 
        yarn build

        # Allow for seeding
        ln -s data/.env .env
    # The deploy hook runs after your application has been deployed and started.
    # Code cannot be modified at this point but the database is available.
    # The site is not accepting requests while this script runs so keep it
    # fast.
    deploy: |
        # Move committed files from temp directory back into mounts.
        ./scripts/handle_mounts.sh

        # Food advisor seed data
        RELATIONSHIPS=$(echo $PLATFORM_RELATIONSHIPS | base64 --decode | jq '.keys')
        if [ $RELATIONSHIPS = 'null' ] && [ ! -f .seed/sqlite-seeded.txt ]; then
            yarn seed
            echo "SQLite database seeded" > .seed/sqlite-seeded.txt
        fi

# The configuration of app when it is exposed to the web.
web:
    # locations:
    #     # For serving the generated OpenAPI specification as part of the documentation.
    #     "/docs/spec":
    #         root: "extensions/documentation/documentation/1.0.0"
    #         allow: true
    #         scripts: false
    #         index:
    #             - full_documentation.json
    commands:
        start: |
            NODE_ENV=production yarn start
            # # Production start on `master`, development server otherwise.
            # if [ "$PLATFORM_BRANCH" = master ]; then
            #     NODE_ENV=production yarn start
            # else
            #     yarn develop
            # fi

# The size of the persistent disk of the application (in MB).
disk: 1024

# The 'mounts' describe writable, persistent filesystem mounts in the application.
mounts:
    # Strapi's cache directory.
    '/.cache':
        source: local
        source_path: cache
    # Allows write access to the SQLite db
    '/.tmp':
        source: local
        source_path: cache
    '/.seed':
        source: local
        source_path: seed
    '/data':
        source: local
        source_path: data
    # Allow for updates to the API (new JSONs) at runtime.
    # 'api':
    #     source: local
    #     source_path: api
    # # Allow GraphQL schema updates (JSON) at runtime.
    # 'exports':
    #     source: local
    #     source_path: exports
    # # Give write access for extension configuration JSONs.
    # 'extensions':
    #     source: local
    #     source_path: extensions
    # # Allow for custom components at runtime.
    # 'components':
    #     source: local
    #     source_path: components
    # Allow for media uploads at runtime.
    'public':
        source: local
        source_path: public