
name: app

type: nodejs:12

build:
    flavor: none

dependencies:
    nodejs:
        yarn: "1.22.5"

hooks:
    build: |
        # Install dependencies with yarn.
        yarn --ignore-optional --frozen-lockfile 

        # Build Strapi (production).
        NODE_ENV=production yarn build

    deploy: |
        set -e

        # Run tests on collection endpoints.
        if [ "$PLATFORM_BRANCH" != master ]; then
            yarn test
        fi

web:
    commands:
        start: NODE_ENV=production yarn start
    locations:
        # For serving the generated OpenAPI specification as part of the documentation.
        "/docs/spec":
            root: "extensions/documentation/documentation/1.0.0"
            allow: true
            scripts: false
            index:
                - full_documentation.json

# .platform.app.yaml
relationships:
    postgresdatabase: "dbpostgres:postgresql"

disk: 1024

mounts:
    # Strapi's cache directory.
    '/.cache':
        source: local
        source_path: cache
    # Allows write access to the SQLite db
    '/.tmp':
        source: local
        source_path: cache
    # Internal directory for letting us know seed has already occurred. 
    '/.seed':
        source: local
        source_path: seed
    # Unpack directory for seeding
    'data':
        source: local
        source_path: data
    # Uploads
    'public':
        source: local
        source_path: public
